### PR TITLE
Exclude setMessageOrder test from FieldMapTests for gcc builds

### LINKED ISSUE #313: Travis constantly fails on gcc builds due to "Failure in setMessageOrder: Unhandled exception: Crash!"
I keep getting the following failure from travis on gcc builds:

```xml
<ut>
  <output>
C++/test/FieldMapTestCase.cpp:37: error: Failure in setMessageOrder: Unhandled exception: Crash!
FAILURE: 1 out of 409 tests failed (1 failures).
Test time: 17.91 seconds.
  </output>
</ut>
```

See for instance #312.

### PR DESCRIPTION
**Pull request by tarc**
This fixes #313

### CODE REVIEW

**Comment by orenmnero** [comment]
Is there an actual bug here? I'm concerned that just commenting out the test is hiding a real problem. Is there some more context here?

**Comment by Ambal** [comment]
Hi, @orenmnero . This test has a bug where "int order[] = {1, 2, 3};" needs a 4th member of value 0. I guess it was fixed in a few other commits already

**Comment by orenmnero** [comment]
Ah it's a bug in the test itself, got it.

**Comment by tarc** [comment]
I think this is fixed then by #279 .

**Comment by tarc** [comment]
@orenmnero , please, while you're at it, consider the issues #311 and #316 and the PRs #312 and #315 .

**Pull request closed without merging**
