### PR TITLE
removed exception specifications

### PR DESCRIPTION
**Pull request by marlowa**

### CODE REVIEW

**Comment by orenmnero** [comment]
GitHub is reporting conflicts, any idea why?

**Comment by marlowa** [comment]
This issue looks to be a duplicate of https://github.com/quickfix/quickfix/pull/218 which was merged to master in March 2019. So I suppose this can be closed as a duplicate.

**Comment by yafiyogi** [comment]
I looks like #218 is not as complete as yours. It's missing changes for the python & ruby code. I'm working on a fix for that.

**Comment by orenmnero** [comment]
@yafiyogi I'm actually going to prefer yours to this PR at this point. The problem is that swig is using exception specifiers in order to generate it's try/catch blocks and rethrow into python and ruby with wrapper types. Without the exception specifiers, the swig bindings will just blow up when one of these methods throws an exception.

We can move to using the %catch specifier in swig, but that will be a lot of work and we will have to be very careful not to miss anything.

**Pull request closed without merging**
