### PR TITLE
Python 3 Support

### PR DESCRIPTION
**Pull request by joncinque**
Add support for Python 3 in quickfix.  To quickly get up and running, you simply need to provide the new flag "--with-python3" on the configure step, and everything else will work out.
This references a lot of the previous work mentioned in #125 and #54 -- big thanks to all the work and feedback there!

In order to maintain compatibility with the Python build, currently at 2.6, many new files have been created specifically for the Python 3 build and test, most of which are suffixed with "-py3" or "_python3".  These are mostly the same as the previous ones except for a few differences
* "has_key" has been removed in favor of "in"
* Exceptions are caught by BaseException using the "as" syntax instead of comma syntax
* in tests, asserts have been changed from "failUnless" to "assertTrue", and "assertEquals" has become "assertEqual"
* the swig interface file uses a few different functions: PyUnicode_AsUTF8(...), PyUnicode_FromString(...), PyLong_FromLong(...)

Note that this PR has changed quickfix.py and QuickfixPython.cpp, so if you need to revert back to using the Python 2 versions, you will need to run src/python/swig.sh and then rebuild to generate them.

### CODE REVIEW

**Comment by pdefrancesco** [comment]
@joncinque @quickfix Any idea how long quickfix support for python3 will take to be available? 

Thanks very much.

**Comment by joncinque** [comment]
It depends when they have time to take a review the changes -- there's a lot there, so I'm happy to help the maintainers in any way possible.

**Comment by onyoo** [comment]
@joncinque I've cloned your version, and it installed on Ubuntu with python 3.6. This may be a noob question but how do I import the package in to a python script? Many thanks for the work you put into this.

**Comment by joncinque** [comment]
Importing it can be a bit tricky directly from source, so I'm working on publishing a usable version on PyPI as "quickfix3" and will provide an update once it's ready.

**Comment by orenmnero** [comment]
I tried running the python3 tests, but it looks like maybe the py3 test files were not checked in?

./test-py3.sh
python3: can't open file 'test/DataDictionaryTestCase-py3.py': [Errno 2] No such file or directory
python3: can't open file 'test/DictionaryTestCase-py3.py': [Errno 2] No such file or directory
python3: can't open file 'test/FieldBaseTestCase-py3.py': [Errno 2] No such file or directory
python3: can't open file 'test/SessionSettingsTestCase-py3.py': [Errno 2] No such file or directory
python3: can't open file 'test/MessageTestCase-py3.py': [Errno 2] No such file or directory

**Comment by joncinque** [comment]
My mistake -- while consolidating the test files I forgot to make that change.  It's good to go now though.

**Comment by orenmnero** [comment]
Thanks. I'm just making some changes so that python2 and 3 can be built at the same time. Basically to do --with-python2 and --with-python3 together will get you both libraries. Should make it easier for us to deploy them both.

**Comment by joncinque** [comment]
Gotcha -- let me know if you need any help with getting that done.

**Comment by pdefrancesco** [comment]
When the fixes are complete, would it be possible to push this to python.org to replace the existing QuickFix version, so that the functional version can be installed via PIP?  Thanks very much for all your help, looking forward to integrating the workable Python3 version.

**Comment by orenmnero** [comment]
Hi Pat, we are working on getting the changes into the existing quickfix deploy process. It will go out under the official quickfix pypi account.

**Comment by pgeez** [comment]
Is there any update on when quickfix with Python3 support will be available on pypi?

**Comment by tengrobert** [comment]
@pgeez I would like to know the same issue. Recently, I'm working on making a FIX project based on python3. I need the pyhon3 FIX module, too. :(

**Comment by joncinque** [comment]
The packaging side still needs to be updated at quickfix/quickfix-package, so I'll work on a pull request to get that going by the end of the week.

**Comment by joncinque** [comment]
The PR for getting deployment done was put in at https://github.com/quickfix/quickfix-package/pull/4 -- let's hope it gets integrated soon!

**Comment by tengrobert** [comment]
@joncinque Thanks for your PR! I really appreciate it. Hope it gets integrated soon!

**Comment by josecarpiocom** [comment]
@joncinque Please, how can we install your commit to start to work with python 3? Thanks :)

**Comment by orenmnero** [comment]
Latest quickfix is on pypi with support for python 2 and 3.

**Comment by nbpkh2** [comment]
can someone create a wheel file for python3.11 and add it https://www.lfd.uci.edu/~gohlke/pythonlibs/#quickfix

**Pull request merged**
