### PR TITLE
Important bug fixes and improvements

### PR DESCRIPTION
**Pull request by Ambal**
This pull request contains several important bug fixes to the codebase:

1) InvalidMessage exception not being thrown when incorrect field tag is being decoded - this resolves issue with failed 'GarbledMessage' acceptance test cases, for example as in pull #91 ;
2) Memory alignment issues in FIX::integer_to_string() method and with shared_array<> class, issue #46 ;
3) Undefined behavior on some compilers during integer deserialization, issue #82 ;
4) Build error on VS2015, issue #81 ;
5) Double precision issues after deserialization, issue #83 ;
6) Error in SocketConnection::processQueue() when socket error is being reported;
7) Error in FieldMap::removeGroup() reported in issue #53 ;
8) Improvement to data field decoding and error reporting, which can now be decoded in the trailer as well as in body and header;
9) Redundant MSXML import is removed on Windows which enables multithreaded project compilation.

Also several performance improvements are included:
1) Improvement for the container type used to store fields in the message;
2) Use of Florian's Loitsch 'double-conversion' library for double de/serialization. It works ~250-300% faster that CRT functions while retaining the same level of precision. https://github.com/google/double-conversion
3) Small message type verification improvement during parsing.

### CODE REVIEW

**Comment by orenmnero** [comment]
Pull request has been applied.

**Comment by troelstm** [comment]
What's the reason that the ToPression (and not ToShortest) variant of the Grisu3 double conversion is chosen?
Right now this produces the slightly unfortunate side effect that any number in the form N * 10**M will fallback to the much slower BigNum conversion, with the net result that that the net improvement is much smaller than it could be in a price stream scenario with sizes in the that form (a 50/50 mix...)

**Comment by Ambal** [comment]
Hi, @troelstm . The main purpose of the change was to improve performance w/o loosing precision for wide range of values. So ToPrecision() turned out to be a better candidate at the time of making this patch. Plus our unit test pack for double conversion is not that good to keep everyone safe.

**Comment by troelstm** [comment]
I appreciate that correctness must have priority over speed.
The problem (we initially made the same mistake) with testing over a wide number range using e.g. random numbers is that it (significantly) can skew the reported speed improvement compared to actual, representative data.
It also seems a bit overkill that we first ask to always have 15 digits generated, and then spend time on removing trailing zero's. :-)
It will try to approach this issue from two angles:
- Try to investigate (via the double conversion project) why the counted case ends up reporting a failure for any number where the fraction becomes less than the error limit before request numbers of digits are generated.
- Look into making the QuickFix double conversion configurable, with the current behavior being the default.

**Comment by Ambal** [comment]
Hi, @troelstm . The 15-digit precision is required by FIX standard. You might also want to check the previous version of the CRT-based double serialization code to see if current code is not an overkill.

**Pull request merged**
