### PR TITLE
Several code fixes and cleanups

### PR DESCRIPTION
**Pull request by Ambal**
Hi,

I've resolved several issues with networking and memory alignment. Also I've fixed issues #53 reported by smmathews and #62 reported by udpip7. Few other bug fixes, code refactorings and cleanups are also present.

### CODE REVIEW

**Comment by SternAndrew** [comment]
Are you no longer going to merge these into quickfix?  Was interest in picking up std::vector<> change off the head.

**Comment by SternAndrew** [comment]
Just for reference I'm seeing the following performance areas show up in my usage of quickfix when generating messages:

`+  14.62%   FIX::FieldMap::calculateLength(int, int, int) const                                             
+  11.55%   FIX::FileStore::set(int, std::string const&)                                                    
+   5.49%   FIX::Message::toString(std::string&, int, int, int) const                                       
+   5.02%   FIX::FieldMap::calculateString(std::string&) const                                              
+   4.90%   FIX::Message::setSessionID(FIX::SessionID const&)                                               
+   3.90%   FIX::FileLog::onOutgoing(std::string const&)                                                    
+   3.71%   FIX::FieldMap::clear()                                                                          
+   3.43%   std::_Rb_tree<int, std::pair<int const, FIX::FieldBase>, std::_Select1st<std::pair<int const, FI
+   3.00%   FIX::FieldMap::calculateTotal(int) const                                                        
+   2.44%   std::_Rb_tree<int, std::pair<int const, FIX::FieldBase>, std::_Select1st<std::pair<int const, FI
+   2.27%   FIX::FieldMap::operator=(FIX::FieldMap const&)                                                  
+   2.26%   FIX::message_order::message_order(int, ...)                                                     
+   2.17%   FIX::FieldMap::addGroupPtr(int, FIX::FieldMap*, bool)                                           
+   2.01%   FIX::FieldMap::~FieldMap()                                                                      
+   2.01%   FIX::message_order::operator=(FIX::message_order const&)                                        
+   1.94%   FIX::FieldMap::setField(FIX::FieldBase const&, bool)                                            
+   1.57%   FIX::Session::sendRaw(FIX::Message&, int)                                                       
+   1.55%   FIX::UtcTimeStampConvertor::convert(FIX::UtcTimeStamp const&, bool)                             
+   1.47%   std::_Rb_tree<int, std::pair<int const, std::vector<FIX::FieldMap*, std::allocator<FIX::FieldMap
`

**Comment by Ambal** [comment]
Hi, SternAndrew. I need to make some cleanup in my branch, then I'll create a pull request. You can still pick whatever you want from my fork: https://github.com/Ambal/quickfix/commits/master

**Comment by SternAndrew** [comment]
Thanks.  I can wait until it is merged to master before I pull.  Is there any estimate on how long it takes from pull request to feedback or integration?

**Comment by Ambal** [comment]
Sometimes it takes year(s) - Oren rarely merges patches with the main branch. So if you experience any issues that are fixed in someone's fork I suggest you to use them right away.

**Comment by SternAndrew** [comment]
That is a really long review process.  I'll watch for your pull request.

**Comment by vanlingen** [comment]
R.,.,

**Comment by Ambal** [comment]
Hi, SternAndrew. You can check pull #92

**Comment by SternAndrew** [comment]
Thanks.

**Pull request closed without merging**
