### PR TITLE
Use googletest instead of UnitTest++ as unit-test framework

### PR DESCRIPTION
**Pull request by Ambal**
Use googletest 1.8.1 as unit-testing framework instead of UnitTest++. Add missing test cases + fix broken tests.

It also fixes issues from #279

### CODE REVIEW

**Comment by Ambal** [comment]
Hi, @mgatny . Any thoughts which unit-test failed during the build? Travis CI says "See test/test-suite.log" w/o publishing the test results to its primary log.

**Comment by mgatny** [comment]
@Ambal heh funny you should mention that... I was just realizing a few days ago that we don't save the test report as an artifact of the build.  I will fix that.

**Comment by mgatny** [comment]
@Ambal in the meantime, I was able to reproduce it locally (ubuntu 16.04, gcc 8.4.0):

```
C++/test/FileStoreTestCase.cpp:157: Failure
Value of: fileStore.get() != nullptr
  Actual: false
Expected: true 
[  FAILED  ] resetBeforeAndAfterWithTestFileManager.FileStoreFactory_FileStoreFromDictionary (0 ms)
```

**Comment by Ambal** [comment]
Hi, @mgatny . I see that you've fixed the Travis CI config, nice! I also fixed the failing unit-test - I forgot to save the pointer to "fileStore" variable before checking it while trying to fix a memory leak. Now we're good, finally.

**Comment by Ambal** [comment]
Hi, @mgatny . I suppose GCC compiler environment is not good on Travis since I get lack of virtual memory error for 3rd time in a row:

> mv -f .deps/OdbcStoreTestCase.Tpo .deps/OdbcStoreTestCase.Plo
> virtual memory exhausted: Cannot allocate memory

Clang is good in the meantime.

**Comment by orenmnero** [comment]
We used to use google test, I'm actually intending to switch to Catch2 for unit testing

**Comment by Ambal** [comment]
Hi, @orenmnero . Why use Catch2? The googletest is included in fused form so it builts as part of ut project.

**Comment by orenmnero** [comment]
Hi Viktor,

Fair question. I don't have time to type a full response but I'll post my
thoughts on this later.

**Comment by Ambal** [comment]
Hi, @orenmnero . If you want to move to Catch2 then it means that we must upgrade codebase to C++11 or later. I'll try to make a patch this weekend to integrate Catch2 instead of googletest which should be too much work.

**Comment by quickfix** [comment]
Yeah, I actually am interested in moving to a more modern C++. 11 or even
14, another topic of discussion I wanted to bring up.

**Comment by Ambal** [comment]
Hi, @orenmnero . It makes sense to release a version of quickfix which will be the last supporting pre-C++11 compilers. C++11 should be mandatory afterwards. Newer standards like C++14 might be a problem since compilers supporting them in Production are not widespread enough yet, unfortunately.

**Comment by quickfix** [comment]
That's good feedback. Despite QuickFIX adhering to older standards, I'm
using c++2a on a daily basis, so 14 seems old to me.

**Comment by orenmnero** [comment]
Move to catch2 has been completed.

**Pull request closed without merging**
